# Generated by Django 4.2 on 2023-04-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('date_of_arrival', models.DateField()),
                ('date_of_departure', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('is_departed', models.BooleanField()),
                ('remaining_seats', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MakesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.flights')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mode', models.CharField(max_length=25)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.flights')),
                ('passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.passenger')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='makespayment',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.passenger'),
        ),
        migrations.AddField(
            model_name='makespayment',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.payment'),
        ),
        migrations.AddField(
            model_name='books',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.flights'),
        ),
        migrations.AddField(
            model_name='books',
            name='passenger_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.passenger'),
        ),
    ]
