# Generated by Django 4.2 on 2023-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_books_flights_makespayment_passenger_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='airfare',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=7),
            preserve_default=False,
        ),
    ]
